services:
  app:
    image: "x246libra/senaon2024:v0.1.0"
    hostname: app.vHost
    container_name: senaon2024_app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-12450}:12450"
    environment:
      - TZ=Asia/Taipei
    networks:
      - senao_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.37
    container_name: mysql
    hostname: mysql.vHost
    restart: unless-stopped
    command:
      [
        mysqld,
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdata
      - MYSQL_USER=caesar
      - MYSQL_PASSWORD=0000
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - senao_network
#    network_mode: "host"

volumes:
  mysql_data:
    name: mysql_data

networks:
  senao_network:
    name: senao_network
    driver: bridge
